steps:
 - name: 'gcr.io/cloud-builders/docker' #use the official docker image
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA', '.']  #builds an image and tags it
images:
 - 'gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA'  #store the image in the container registry


